name: letswashlet
description: washlet simulator.
publish_to: 'none'
version: 1.1.6+16

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android: ^4.8.2
  webview_flutter: ^4.13.0
  # Firebase Analytics
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_app_check: ^0.3.2+10
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  # Audio Player
  just_audio: ^0.10.4
  # Vibration
  vibration: ^3.1.3
  # Admob
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1
  #env
  flutter_dotenv: ^5.2.1
  #MVVM
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App Splash
  flutter_native_splash: ^2.4.6

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "#ffffff"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
    - assets/.env

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: cornerStone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
